# Generated by Django 5.2.4 on 2025-07-15 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_document_financialentry_project_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
