# Generated by Django 5.2.4 on 2025-07-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_unit_created_at_unit_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('Heavy Machinery', 'Heavy Machinery'), ('Car', 'Car'), ('Truck', 'Truck'), ('Semi Truck', 'Semi Truck'), ('Boat', 'Boat'), ('Motorcycle', 'Motorcycle'), ('Tools', 'Tools'), ('Equipment', 'Equipment')], default='Tools', max_length=50),
        ),
    ]
