# Generated by Django 5.2.5 on 2025-08-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0027_businessasset_filestorage_finance_iftareport_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='category',
            field=models.CharField(blank=True, choices=[('BOL', 'BOL'), ('POD', 'POD'), ('Invoice', 'Invoice'), ('Insurance', 'Insurance'), ('Registration', 'Registration'), ('IFTA', 'IFTA'), ('Logs', 'Logs'), ('Permits', 'Permits'), ('Maintenance', 'Maintenance'), ('Driver Docs', 'Driver Docs'), ('Load Docs', 'Load Docs'), ('Documents', 'Documents'), ('Other', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
