# Generated by Django 5.2.5 on 2025-08-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0028_filestorage_category_filestorage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='type',
            field=models.CharField(blank=True, choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10, null=True),
        ),
    ]
