# Generated by Django 5.2.5 on 2025-08-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0031_personaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='ai_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
