# Generated by Django 5.2.5 on 2025-08-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0032_personaltask_ai_suggested_personaltask_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='ai_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PersonalProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='personal_project_media/')),
                ('url', models.URLField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='formula.personalproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
