# Generated by Django 5.2.4 on 2025-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0034_savingsgoal_savingsplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessasset',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessasset',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessasset',
            name='miles',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
