# Generated by Django 5.2.4 on 2025-08-12 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0035_businessasset_category_businessasset_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='formula.load'),
        ),
        migrations.AddField(
            model_name='route',
            name='end_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='end_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
