# Generated by Django 5.2.4 on 2025-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0036_filestorage_load_route_end_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfinancialentry',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalfinancialentry',
            name='type',
            field=models.CharField(blank=True, choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10, null=True),
        ),
    ]
