# Generated by Django 5.2.4 on 2025-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0038_personalmonthlyitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalmonthlyitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
