# Generated by Django 5.2.4 on 2025-08-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0039_alter_personalmonthlyitem_id'),
        ('formula', '0039_personaltask_estimated_hours'),
    ]

    operations = [
    ]
