# Generated by Django 5.2.4 on 2025-08-14 19:41

import formula.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0041_personalschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalschedule',
            name='data',
            field=models.JSONField(default=dict, encoder=formula.encoders.PrettyJSONEncoder),
        ),
    ]
