# Generated by Django 5.2.4 on 2025-09-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0042_alter_personalschedule_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/')),
                ('original_name', models.CharField(max_length=255)),
                ('detected_title', models.CharField(blank=True, default='', max_length=500)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('assignment_type', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(blank=True, default='uploaded', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assign_uploads',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('output_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='formula.upload')),
            ],
            options={
                'db_table': 'assign_run_results',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_turns', to='formula.upload')),
            ],
            options={
                'db_table': 'assign_chat_turns',
                'ordering': ['id'],
            },
        ),
    ]
