# Generated by Django 5.2.4 on 2025-09-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0043_upload_runresult_chatturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('debt', 'Debt'), ('savings', 'Savings'), ('investment', 'Investment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='monthly_contribution',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Planned monthly contribution allocated specifically to this goal', max_digits=12),
        ),
    ]
